FROM python:3.8

WORKDIR /Users/selenia/DigitalTools_project/Homework/Week2

COPY . .

# install dependencies
RUN pip install matplotlib
RUN pip install pandas


CMD ["python", "Week2.py"]

#commands to run in the terminal:
# docker build -t yoursuername/plot .
# docker images
# docker run yoursuername/plot
 